### PR TITLE
Fully support Active Record 6.1

### PR DESCRIPTION
**Pull request by dsantosmerino**
As @Kuchick mentioned #48, the current code doesn't support Active Record 6.1. The main change is about retrieving the database config, while being backward compatible (related Rails PR - https://github.com/rails/rails/pull/37253).
Also added Rails 6.1 in the CI matrix to be sure that is working as expected.

This is my first attempt to contribute here, so please let me know if you need anything to be adapted :pray:

### CODE REVIEW

**Comment by botandrose** [comment]
Hi @dsantosmerino! This looks really good. Thanks for putting this together. I'm not immediately certain why Codecov is complaining about loss of test coverage. Can you see if you can figure that out so we can stay at 100% coverage? Once that's clear I'll be happy to merge and release this!

**Comment by botandrose** [comment]
@dsantosmerino Yo, I found myself with some free time today, and I want to get this merged and released ASAP, so I figured out what was going on with the missing test coverage. Turns out that the refactor exposed missing coverage that was there all along! Before the refactor, all of this was on one line: 
```ruby
models.select(&:connection_pool).detect { |m| m.connection_pool.spec.config[:database] == database_name }
```
`models` was always an empty array, though, in the existing tests, so the line was technically covered, but the block was never actually executed. Your refactoring split that block off into a new line and with a new extracted method, and exposed this issue.

This is great! I've written a few tests to resolve this missing coverage, so I'm going to merge this PR, and then push the new tests on top to get back to 100%.

Thanks for your great work here!

**Comment by Kuchick** [comment]
@dsantosmerino and @botandrose  thanks!
@botandrose Can these changes be added to database_cleaner v1.8 (as 1.8.6) to have Rails 6.1 support because of 2.0 version is in beta?

**Comment by botandrose** [comment]
Just released v2.0 of all gems!

**Pull request merged**
